<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW1504" ignored="26" name="Default test" tests="10" failures="5" timestamp="04 Nov 2019 11:57:35 GMT" time="0.066" errors="0">
  <testcase name="additionChecker" time="0.007" classname="com.jstech.calculatortestatsk.TestCalculator"/>
  <testcase name="additionChecker" time="0.001" classname="com.jstech.calculatortestatsk.TestCalculator"/>
  <testcase name="additionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator"/>
  <testcase name="additionChecker" time="0.001" classname="com.jstech.calculatortestatsk.TestCalculator"/>
  <testcase name="additionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator"/>
  <testcase name="additionChecker" time="0.001" classname="com.jstech.calculatortestatsk.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [5.0] but found [9.0]">
      <![CDATA[java.lang.AssertionError: expected [5.0] but found [9.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.jstech.calculatortestatsk.TestCalculator.additionChecker(TestCalculator.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- additionChecker -->
  <testcase name="additionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [4.0] but found [8.0]">
      <![CDATA[java.lang.AssertionError: expected [4.0] but found [8.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.jstech.calculatortestatsk.TestCalculator.additionChecker(TestCalculator.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- additionChecker -->
  <testcase name="additionChecker" time="0.001" classname="com.jstech.calculatortestatsk.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-2.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: expected [-2.0] but found [2.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.jstech.calculatortestatsk.TestCalculator.additionChecker(TestCalculator.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- additionChecker -->
  <testcase name="additionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.jstech.calculatortestatsk.TestCalculator.additionChecker(TestCalculator.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- additionChecker -->
  <testcase name="additionChecker" time="0.001" classname="com.jstech.calculatortestatsk.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [6.0] but found [-6.0]">
      <![CDATA[java.lang.AssertionError: expected [6.0] but found [-6.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.jstech.calculatortestatsk.TestCalculator.additionChecker(TestCalculator.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- additionChecker -->
  <testcase name="testSubtractionBothNegative" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testSubtractionBothNegative -->
  <testcase name="testDivideNegativeNumerator" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testDivideNegativeNumerator -->
  <testcase name="negativeTestAddition" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- negativeTestAddition -->
  <testcase name="testMultiplyTwo" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testMultiplyTwo -->
  <testcase name="testMultiplyIdentity" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testMultiplyIdentity -->
  <testcase name="testSubtractionNegative" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testSubtractionNegative -->
  <testcase name="testMultiplyTwoNegatives" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testMultiplyTwoNegatives -->
  <testcase name="negativeTestMultiply" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- negativeTestMultiply -->
  <testcase name="testAddition" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testAddition -->
  <testcase name="testNegativeInteger" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testNegativeInteger -->
  <testcase name="subtractionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- subtractionChecker -->
  <testcase name="testAdditionIdentity" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testAdditionIdentity -->
  <testcase name="negativeTestDivideByZero" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- negativeTestDivideByZero -->
  <testcase name="multiplicationChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- multiplicationChecker -->
  <testcase name="testMultiplyWithZero" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testMultiplyWithZero -->
  <testcase name="testNegativeIntegerP" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testNegativeIntegerP -->
  <testcase name="testDivideNegativeDenominator" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testDivideNegativeDenominator -->
  <testcase name="testPositiveIntegerN" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testPositiveIntegerN -->
  <testcase name="testAdditionNegative" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testAdditionNegative -->
  <testcase name="negativeTestDivide" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- negativeTestDivide -->
  <testcase name="negativeTestSubtract" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- negativeTestSubtract -->
  <testcase name="testDivideByZero" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testDivideByZero -->
  <testcase name="testPositiveInteger" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testPositiveInteger -->
  <testcase name="testDivide" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testDivide -->
  <testcase name="divisionChecker" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- divisionChecker -->
  <testcase name="testSubtraction" time="0.0" classname="com.jstech.calculatortestatsk.TestCalculator">
    <ignored/>
  </testcase> <!-- testSubtraction -->
</testsuite> <!-- Default test -->
